### ISSUE TITLE
Capture button is not working.

### ISSUE THREAD

**Issue by FredBezies** [chrisfair/kazam#1]
After building python-cairo-git (on archlinux), I noticed capture button is not working.

Here is the traceback I got in terminal : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/kazam/app.py", line 677, in cb_record_clicked
    self.run_counter()
  File "/usr/lib/python3.5/site-packages/kazam/app.py", line 1010, in run_counter
    self.countdown = CountdownWindow(self.indicator, show_window=prefs.countdown_splash)
  File "/usr/lib/python3.5/site-packages/kazam/frontend/window_countdown.py", line 93, in __init__
    self.window.input_shape_combine_region(region)
KeyError: 'could not find foreign type Region'
```

Any idea ?

**Comment by chrisfair** [comment]
Not yet....I just forked this the other day will look

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: FredBezies notifications@github.com Date: 10/9/16  2:42 AM  (GMT-07:00) To: chrisfair/kazam kazam@noreply.github.com Subject: [chrisfair/kazam] Capture button is not working. (#1) 
After building python-cairo-git (on archlinux), I noticed capture button is not working.

Here is the traceback I got in terminal : 

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/kazam/app.py", line 677, in cb_record_clicked
    self.run_counter()
  File "/usr/lib/python3.5/site-packages/kazam/app.py", line 1010, in run_counter
    self.countdown = CountdownWindow(self.indicator, show_window=prefs.countdown_splash)
  File "/usr/lib/python3.5/site-packages/kazam/frontend/window_countdown.py", line 93, in **init**
    self.window.input_shape_combine_region(region)
KeyError: 'could not find foreign type Region'

Any idea ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chrisfair/kazam","title":"chrisfair/kazam","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/chrisfair/kazam"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Capture button is not working. (#1)"}],"action":{"name":"View Issue","url":"https://github.com/chrisfair/kazam/issues/1"}}}
